name: Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: ./
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
